robots:
  - id: R1
    start_location: [-0.5, -4.0]
    speed_m_s: 0.25

  - id: R2
    start_location: [0.5, -4.0]
    speed_m_s: 0.25

  - id: R3
    start_location: [-0.5, -4.5]
    speed_m_s: 0.25
  
  - id: R4
    start_location: [0.5, -4.5]
    speed_m_s: 0.25